[project]
name = "tinyclientcli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.27.0",
    "mcp>=1.0.0",
    "pyfiglet>=1.0.2",
    "rich>=13.7.0",
]
